"""Add initial data

Revision ID: 602465645579
Revises: 1b76faf7a387
Create Date: 2025-04-06 18:28:34.925069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602465645579'
down_revision: Union[str, None] = '1b76faf7a387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.bulk_insert(
        sa.table("permissions", sa.Column("id"), sa.Column("name"), sa.Column("description")),
        [
            {"id": 1, "name": "create_party", "description": "Allows users to create a party"},
            {"id": 2, "name": "update_party", "description": "Allows users to update their party"},
            {"id": 3, "name": "delete_party", "description": "Allows users to delete their party"},
            {"id": 4, "name": "change_profile_image", "description": "Allows users to update profile image"}
        ]
    )

    op.bulk_insert(
        sa.table("roles",  sa.Column("id"), sa.Column("name"), sa.Column("description")),
        [
            {"id": 1, "name": "user", "description": "Basic user role"},
            {"id": 2, "name": "admin", "description": "Administrator role"}
        ]
    )

    op.bulk_insert(
        sa.table("permissions_roles", sa.Column("role_id"), sa.Column("permission_id")),
        [
            {"role_id": 1, "permission_id": 1},
            {"role_id": 1, "permission_id": 2},
            {"role_id": 1, "permission_id": 3},
            {"role_id": 1, "permission_id": 4}
        ]
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
