"""added party model

Revision ID: 6fa1dd44ad78
Revises: 409a2058592a
Create Date: 2025-04-03 16:43:10.856896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa1dd44ad78'
down_revision: Union[str, None] = '409a2058592a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_party', sa.String(length=255), nullable=False),
    sa.Column('url_image_full', sa.String(length=500), nullable=False),
    sa.Column('name_organizer', sa.String(length=255), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('name_town', sa.String(length=255), nullable=False),
    sa.Column('name_country', sa.String(length=255), nullable=False),
    sa.Column('name_type', sa.String(length=255), nullable=False),
    sa.Column('text_entry_fee', sa.Float(), nullable=True),
    sa.Column('text_more', sa.Text(), nullable=True),
    sa.Column('url_organizer', sa.String(length=500), nullable=True),
    sa.Column('url_party', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_id'), 'parties', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parties_id'), table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
