"""added user_id in parties

Revision ID: 89f6b3e373b8
Revises: 6fa1dd44ad78
Create Date: 2025-04-04 10:10:54.293928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f6b3e373b8'
down_revision: Union[str, None] = '6fa1dd44ad78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'parties', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parties', type_='foreignkey')
    op.drop_column('parties', 'user_id')
    # ### end Alembic commands ###
